### ISSUE TITLE
Title add canvas position (x, y) and canvas size (w, h)

### ISSUE THREAD

**Issue by A-312** [Eskimon/draw-on-stream-telestrator#1]
![image](https://user-images.githubusercontent.com/18501150/66046170-77ebbf00-e525-11e9-9e26-d1a91484b358.png)

(FR)
> Mais oui c'est ca que j'avais oublié de faire !! Rajouter dans le titre de la fenetre la position + taille du caneavas !!
> **Eskimon**

**Comment by Eskimon** [comment]
Implemented in https://github.com/Eskimon/draw-on-stream-telestrator/commit/22e0c80e951697f1d3e4bcb348834d0c7b6c1105
