### ISSUE TITLE
Shortcut to recover after sliding opacity to full transparency?

### ISSUE THREAD

**Issue by BdR76** [Eskimon/draw-on-stream-telestrator#3]
Pretty cool program, but when you accidentally move the transparency slider to minimum (full transparency) the window is invisible, and unless you can blindly find the slider there is no way to make it visible again(?).

Pressing `ctrl +` or `ctrl -` doesn't seem to change the opacity, although pressing just `+` or `-` does change the line size. I know you can recover by removing the `config.json` file, or manually editing it to `"alpha": 80,`, but I mean there's no shortcut or something?

Btw I tried both the `painter-32bits.exe` and `painter-64bits.exe` on Windows 10.

EDIT: btw when you undo pen lines, it works per individual line segment. imho it should work on the entire lines, so when you draw a roman XI you should be able to undo it with just 3 undo clicks

**Comment by Eskimon** [comment]
I've just added a `ctrl+r` shortcut to solve this. Sorry for the long wait! It should be available right now in the [v1.2 release](https://github.com/Eskimon/draw-on-stream-telestrator/releases/tag/v1.2)
